### ISSUE TITLE
Request `textDocument/codeAction` failed.

### ISSUE THREAD

**Issue by jens1o** [Jason-Rev/vscode-spell-checker#158]
```
[Error - 9:59:37 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'uri' of undefined
  Code: -32603 
```
I'm getting this all the time when I click in a file and move the cursor since updating to `v1.5`.

**Comment by devmattrick** [comment]
I'm getting this issue as well. +1

**Comment by benc-uk** [comment]
Getting the same. It's extra annoying as the error causes the output tab of the terminal to jump into focus, making it impossible to use the terminal.
I'm going to have to disable the extension for now. Hope it gets fixed soon

**Comment by Jason3S** [comment]
@jens1o and @benc-uk are you using Windows?

**Comment by benc-uk** [comment]
Yep

**Comment by Jason3S** [comment]
I have put out a patch that rolls back most of the changes related to 1.5.0. I'll publish a new version when I get the issues for Windows fixed.

**Comment by Jason3S** [comment]
Thank you for brining up the issues.

**Comment by Jason3S** [comment]
This should be fixed with 1.6.0.

**Comment by aminpaks** [comment]
Still happens on vscode v1.24.1 with spell-checker v1.6.10 :|

**Comment by Jason3S** [comment]
@aminpaks Can you please open a new issue?
Please refer to this issue and add any relevant information.

* The stack trace would be helpful.
* Your environment
* The type of file opened.
* Steps to reproduce

Thank you.
